## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

import ns3waf
import os

def configure(conf):
    ns3waf.check_modules(conf, ['core', 'network','internet', 'applications', 'csma', 'mobility', 'wifi', 'dce-umip', 'netlink', 'dce', 'dce-quagga', 'netanim', 'tpa'], mandatory = True)

def build(bld):
#    linkerpath=os.path.abspath(os.path.join('..', 'elf-loader','ldso'))
    bld.build_a_script('dce', needed = ['core', 'network', 'internet', 'applications', 'csma', 'mobility', 'wifi', 'dce-umip', 'netlink', 'dce', 'dce-quagga', 'netanim', 'tpa'],
				  target='bin/mipv6test',
				  source=['mipv6test.cc'],
#				  linkflags=['-Wl,--dynamic-linker=' + linkerpath ]
#				  linkflags=['-L/usr/local/lib'],
#				  lib=['foolib']
				  )

